seed: 42
model:
  arch: glass_detection_with_depth
  backbone_name: resnet50
  backbone_pretraining: imnet
  depth_pretraining: none
  pose_pretraining: none
  enable_imnet_encoder: False
  segmentation_name: joint_seg_depth_dec

training:
  epochs: 10
  log_path: 'runs'
  amp: True
  optimizer:
    name: 'sgd'
    lr: 1.0e-3
    weight_decay: 0.0005
    momentum: 0.9
  resume:
  print_interval: 100
  batch_size: 2
  val_batch_size: 2
  num_workers: 8
  lr_schedule:
  monodepth_lambda: 0.0
  feat_dist_lambda: 0.0
data:
  dataset: vgsd
  height: 416
  weidth: 416
  shuffle_trainset: True

  

